server:
  port: 8088
spring:
  application:
    name: consumer_hystrix_turbine
user:
  url: http://localhost:7900/user/
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://user:123@localhost:9900/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
turbine:
  aggregator:
    cluster-config: default
  app-config: CONSUMER-ORDER-HYSTRIX, consumer_hystrix_dashboard
  cluster-name-expression: "'default'"
